// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _WEB315_Summer22_ThemeDriving.Migrations
{
    [DbContext(typeof(ThemeDrivingContext))]
    [Migration("20230220192909_modelnumber")]
    partial class modelnumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("_WEB315_Summer22_ThemeDriving.Models.ThemeDriving", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarModel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .HasColumnType("TEXT");

                    b.Property<string>("colour")
                        .HasColumnType("TEXT");

                    b.Property<string>("distance")
                        .HasColumnType("TEXT");

                    b.Property<int>("modelnumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("ThemeDriving");
                });
#pragma warning restore 612, 618
        }
    }
}
